var canvas = document.getElementById("canvas");
var fieldRow = 10;
var fieldCol = 20;
var blockSize = 30;
var canvasSizeX = fieldRow * blockSize;
var canvasSizeY = fieldCol * blockSize;
canvas.width = canvasSizeX;
canvas.height = canvasSizeY;
canvas.style.border = "3px solid #555";
var gameBoard = canvas.getContext("2d");
gameBoard.lineWidth = 10;
gameBoard.fillStyle = "black";
gameBoard.fillRect(0, 30, blockSize, blockSize);
var total = 0;
var score = document.getElementById("score");
score.innerHTML = "score: ".concat(total);
